name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 3 */3 * *"   # a cada 3 dias às 03:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Edge Function (fail if not 200)
        run: |
          URL="https://wdiwtkzxpcqzsolzryzc.supabase.co/functions/v1/ping"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")

          echo "HTTP status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Ping falhou. Esperado 200."
            exit 1
          fi

          echo "Ping OK. Projeto acordado e atento."